# Generated by Django 2.2.3 on 2019-10-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='description')),
                ('picture', models.ImageField(blank=True, upload_to='pic/')),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
